[project]
name = "un-impacts"
version = "0.1.0"
description = "Showcase of impacts across the UN System."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.1",
]
